UCL/TDMS

- LICENSE
> Add GPLv3 licence

- .github/workflows/tests.yml
- tdms/CMakeLists.txt
This implements point 1.i in #41.
> Compile TDMS with `-Wall`

- .github/workflows/tests.yml
- tdms/CMakeLists.txt
- tdms/include/argument_parser.h
- tdms/src/argument_parser.cpp
- tdms/tests/unit/test_openandorder.cpp
Adds a starting point for catch2 unit tests
> Unit tests

- .github/workflows/matlab_tests.yml
- tdms/matlab/iteratefdtd_matrix.m
- tdms/tests/matlab/README.md
- tdms/tests/matlab/data/pstd_input_file.m
- tdms/tests/matlab/data/pstd_input_file_2D.m
- tdms/tests/matlab/data/pstd_input_file_3D.m
- tdms/tests/matlab/run_tests.m
- tdms/tests/matlab/test_iteratefdtd_matrix.m
> Add check on field names

- tdms/matlab/fdtdduration.m
- tdms/matlab/minsteps_fdtd.m
- tdms/matlab/minsteps_pstd.m
- tdms/tests/matlab/test_fdtdduration.m
> Add MATLAB unit tests

- .github/workflows/linting.yml
- .pre-commit-config.yaml
- doc/developers.md
- tdms/tests/system/test_arc01.py
- tdms/tests/system/test_arc02.py
- tdms/tests/system/test_arc03.py
- tdms/tests/system/utils.py
Now Python is being introduced to run tests, this PR introduces config and a GH actions job to enforce linting on the codebase. This still needs some developer documentation adding, so opening as a draft for now.
> Add linting for Python code

- doc/developers.md
- tdms/CMakeLists.txt
We might not want this. 
"It's one specific system" -- @giordano 
I'm of the opinion that if you're a developer the likelihood is a) you're a UCL person, b) you read warnings... and therefore these should/can go in.
> Experimental myriad instructions.

- tdms/src/iterator.cpp
> Remove duplicate dt variable

- .github/workflows/macos_tests.yml
Latest is 11 so this should workaround actions/runner-images/issues/6225
> Fix macOS build

- .github/workflows/macos_tests.yml
My fault - missed this when reviewing.
> Fix syntax not caught in review

- tdms/tests/system/test_arc12.py
- tdms/tests/system/test_arc13.py
Two more boilerplate-thonic test scripts. All of this should be improved with #101 but prefer to get these tests in early, and deboilerplate later.
Particularly would like these tests running for #139.
***
Fix #140
> Add Peter's FDTD tests.

- tdms/CMakeLists.txt
Going via a one-liner PR to separate out any problems we might have from **_this_** change, vs my eventual fix to #129 which --I think-- will need some `std::filesystem` stuff.
At least trivial PRs are easy to review 😛. 
If you approve: feel free to just merge in at whatever point seems sensible in your merge chain #130 → #80 → #131(?)
> C++ 14 → 17.

- tdms/CMakeLists.txt
- tdms/include/field.h
- tdms/include/interpolate.h
- tdms/include/interpolation_methods.h
- tdms/include/simulation_parameters.h
- tdms/matlabio/matlabio.h
- tdms/src/fields/base.cpp
- tdms/src/fields/electric.cpp
- tdms/src/fields/magnetic.cpp
- tdms/src/interpolate.cpp
- tdms/src/interpolation_methods.cpp
- tdms/src/iterator.cpp
- tdms/src/simulation_parameters.cpp
- tdms/tests/unit/test_field_interpolation.cpp
- tdms/tests/unit/test_interpolation_determination.cpp
- tdms/tests/unit/test_interpolation_functions.cpp
> Revert "Replace Cubic with Band Limited Interpolation"

- .github/workflows/linux_tests.yml
- .github/workflows/macos_tests.yml
- .github/workflows/windows_tests.yml
> Forgot to remove derivative_type from the compile flags.

- .github/workflows/windows_tests.yml
A messy development branch ultimately to be merged into #157 (itself an experimental dev branch).
> HDF5 working on Windows build.

- tdms/include/argument_parser.h
- tdms/include/field.h
- tdms/include/globals.h
- tdms/include/interpolation_methods.h
- tdms/include/iterator.h
- tdms/src/argument_parser.cpp
- tdms/src/fields/electric.cpp
- tdms/src/fields/magnetic.cpp
- tdms/src/interpolation_methods.cpp
- tdms/src/iterator.cpp
- tdms/src/openandorder.cpp
- tdms/tests/unit/test_interpolation_determination.cpp
- tdms/tests/unit/test_interpolation_functions.cpp
Following on from #196 & #198 weird wrong diff bug.
> Interpolation method as a toggle

- CONTRIBUTING.md
Of course, I missed *one* link. 
I'm happy to report that the PR template, which I've just deleted, works well though. 👍
* Relates to #230
> Link to the template chooser page.

- README.md
This is the second aesthetics bug I've introduced in the last 24 hours.
You gotta watch me.
> Fix badge.

- tdms/tests/include/unit_test_utils.h
> Remove (unused) using directive from header.

- tdms/include/globals.h
This should go in after
* #262 
And we can tag... the merge commit?
> Fallback to v1 if no tag provided (or no git repo)

- CITATION.cff
- README.md
Now we have a Zenodo DOI. Put it everywhere.
Also ping @giordano for interest/expert eyes.
* Closes #258.
> Add Zenodo DOI to README.md and CITATION.cff.

- .github/workflows/ci.yml
>  Just in case there are any shenanigans down the road
Hopefully, if there's any missing .dll or library error (or some other problem with the executable) we catch it here.
> Add a smoke test to CI.

- README.md
- doc/developers.md
@willGraham01 your comments from #296 that got lost.
Plus:
... as requested by @prmunro yesterday.
> A few doc tweaks,

- .github/workflows/doc.yml
Broken LaTeX build scheduling.
* Fixes #348 
...
Manually here on CI 😅
> Fix LaTeX build config.

- .github/dependabot.yml
Should make maintenance of CI a _little bit_ easier and more automated.
> Create dependabot config for GitHub actions
