README.md, tdms/src/openandorder_PSTD.cpp, tdms/src/tdms_iterator.cpp
- Closes #38 
- Moves the OMP print statement from the main function into the only parallelised function
=> OpenMP documentation

tdms/include/interpolate.h, tdms/matlabio/matlabio.h, tdms/src/interpolate.cpp
Starts a refactor of `interpolate.cpp` by removing the unused return codes in favour of void functions that throw runtime errors. Given the reasonably sized diff I think it's perhaps worth reviewing this first and merging, rather than waiting to add everything in #44 in(?)
=> Throw exceptions rather than return codes

examples/arc_01/run_pstd_bscan.m
#54 Fixes error thrown in `run_pstd_bscan.m` by getting MATLAB to create the directories `gridfiles/`, `in/`, and `out/`, if they do not exist prior to running the script.
Also some other things I'm dumping here as afterthoughts:
- Rather than displaying the figures in MATLAB, we could just save them as images? This would mean the MATLAB GUI wouldn't need to load up every time, and we can stick to something like `matlab -nodesktop -nosplash -r run_pstd_bscan` in the command line.
- On a note related to the above, MATLAB does not exit upon completion of a script, unless you explicitly give it the `exit()` command at the end of the script!
=> #54 run_pstd_bscan.m now creates missing directories

.github/workflows/linux_tests.yml, .github/workflows/windows_tests.yml, tdms/CMakeLists.txt
This is a more standard way to enable/disable CMake tests, instead of (ab)using the build type.
=> Use CMake `CTest` module to choose whether to build tests

tdms/CMakeLists.txt, tdms/cmake/targets.cmake, tdms/src/argument_parser.cpp, tdms/src/openandorder.cpp
This PR adds a logging library, specifically [spdlog](https://github.com/gabime/spdlog) to e.g. allow for debug logging to be turned on/off depending on the build type. I've tried this out by both brew installing spdlog (and defining `spdlog_DIR` for CMake to find it) and also letting `FetchContent_MakeAvailable` do it's thing and both seem to work well. To turn on debug logging:
```
cmake <other args> -DCMAKE_BUILD_TYPE=Debug
```
To silence all logging (excellent suggestion from @samcunliffe !) run the executable with
```bash
tdms input.mat output.mat -q
```
***
Also includes simple example usage in the argument parser, just for an outline. Seems like it's thread safe too:
```diff
--- a/tdms/src/iterator.cpp
+++ b/tdms/src/iterator.cpp
@@ -32,6 +32,9 @@
#include "numerical_derivative.h" …
```
=> Adds a spdlog logging

.github/workflows/doxygen-gh-pages.yml, .github/workflows/macos_tests.yml, README.md, tdms/CMakeLists.txt, tdms/tests/unit/test_interpolate.cpp
Got it working on 🍎 !
Thanks for @giordano 's top-tip to use [this tmate action](https://github.com/marketplace/actions/debugging-with-tmate) to help debugging.
Unfortunately it's yet another separate build with a YML file that is 90% the same as the Linux and Windows ones. But on the plus: we get another badge.
Good news: it found a genuine (minor) bug. 🐛
=> [CI] Add macos testing

.gitignore, doc/developers.md, tdms/tests/README.md, tdms/tests/system/test_arc08.py
Adding system tests of the steady state mode. This is 1/4 of #30. Peter kindly provided a [fast version](https://github.com/UCL/TDMS/issues/30#issuecomment-1249187562) (physically meaningless, but can be used for testing).
Note that the test will *fail* until #94 is merged.
@dstansby, @giordano, @prmunro you're very welcome to join the review and/or comment if you have time to do so.
Since I'm tweaking the documentation, language/clarity and section logic comments are also very welcome. No comment is too picky or too minor.
=> Adding steady state tests.

doc/developers.md, tdms/tests/system/test_arc09.py, tdms/tests/system/test_arc10.py, tdms/tests/system/utils.py
This PR is adds two more test cases provided by @prmunro (thanks!) and another 2/4 of #30: a test w/ exi present and a test w/ exdetintegral.
The first is very fast:
```
py.test tdms/tests/system/test_arc10.py  73.70s user 10.40s system 563% cpu 14.916 total
```
The second a little slower (but not the slowest):
```
py.test tdms/tests/system/test_arc09.py  704.33s user 40.89s system 681% cpu 1:49.37 total
py.test tdms/tests/system/test_arc03.py  1171.14s user 66.51s system 527% cpu 3:54.44 total
```
And notably I had to tweak the HDF5File class to cope with groups.
=> Two more system tests.

tdms/src/electric_field.cpp, tdms/src/iterator.cpp, tdms/tests/system/test_arc08.py
I updated the code so that steady state mode is now correct. I picked up a bug introduced during recent refactoring work, whereby there are now two variables storing dt, in particular:
params.dt
dt
both are used. This becomes a problem since in some instances dt can be changed within the code. After refactoring, params.dt was not updated, leading to incorrect behaviour. I will add this as an issue.
=> Fix to steady state mode

tdms/CMakeLists.txt, tdms/cmake/targets.cmake
I missed this when testing #92. 
→ We also need to grab catch2 over ssh if the `GIT_SSH` option is set. 
This PR allows us to also build the tests on Myriad. Or if the user just prefers ssh.
=> Obey the GIT_SSH option also for catch2.

.github/workflows/linux_tests.yml, .github/workflows/macos_tests.yml, .github/workflows/matlab_tests.yml, .github/workflows/windows_tests.yml
The underlying issue is an update ~~of Xcode used in~~ the runner images: actions/runner-images/issues/6225
This is neater and targets main (#117 is to Will's branch).
~~🚧 testing the concurrency to save 🌳🔨~~
Concurrency is working ✅
=> Fix the macOS build and add concurrency.

.github/workflows/linux_tests.yml, .github/workflows/macos_tests.yml, .github/workflows/windows_tests.yml, doc/developers.md, pytest.ini, tdms/tests/system/test_fdtd.py, tdms/tests/system/utils.py
Adds an example FDTD test (current functionality). Not necessarily meaningful, but a run of the example scripts with FD compile flag. This at least tests against regression.
Also runs the unit tests with the FD flag in the CI for BUILD_TESTING builds. And update the documentation.
***
- #121 
- #119
=> Add FDTD test.

.github/workflows/macos_tests.yml
Continues #182.
Sorry for the trivial PR noise. I should have noticed this last night, but I was too happy that I had fixed the build.
`actions/setup-python@v2` uses some old Node.js and kicks out [warnings on the build](https://github.com/UCL/TDMS/actions/runs/3456729198). Updating to `v4` updates everything and clears the warnings. Completely transparent change for us.
=> Node.js 12 warnings.

tdms/tests/include/unit_test_utils.h, tdms/tests/unit/field_tests/test_TDFieldExporter2D.cpp
Adding tmp directory function which was developed for #181, but seems like it's useful already.
@alessandrofelder mentioned that there might be a cleaner(?) way to do this in CMake (which I haven't investigated). But mine is now only a few lines of C++ from the `std` library. So hopefully not too clunky.
***
The `*_utils.h` file has a messy diff because I changed the indentation. I'd recommend [turning whitespace off](https://github.blog/2018-05-01-ignore-white-space-in-code-review/) (if you haven't already done so).
=> A temporary directory utility function for file I/O tests.

tdms/tests/include/array_test_class.h
Fixes the MacOS requirement that `const static` be used in place of `const` for private class attributes that are used to declare arrays.
=> Samcunliffe array test class

tdms/tests/include/unit_test_utils.h, tdms/tests/unit/matlab_benchmark_scripts/benchmark_test_interpolation_functions.m, tdms/tests/unit/test_BLi_vs_cubic_interpolation.cpp, tdms/tests/unit/test_interpolation_functions.cpp, tdms/tests/unit/test_numerical_derivative.cpp
Uses `Catch2`'s sectioning abilities to reduce the amount of code repetition in the tests that were introduced in #80. Closes #125 .
This is mainly just using sections to breakout the few portions of each of these tests that are different - creation of the data, the exact function values, etc.
Sadly it's impossible to go the full throw and drop the distinction between complex-valued and real-valued function tests (unless we want to treat "real" functions as "complex" functions with no imaginary part, but then we aren't testing the time-domain stuff).
**Half the diff** is an indentation bug in `unit_test_utils.m`. Not sure why this appears.
=> Reduce code duplication in unit tests introduced by #80

tdms/tests/include/abstract_array_test_class.h, tdms/tests/include/array_test_class.h, tdms/tests/unit/array_tests/test_CollectionBase.cpp, tdms/tests/unit/array_tests/test_ComplexAmplitudeSample.cpp, tdms/tests/unit/array_tests/test_DTilde.cpp, tdms/tests/unit/array_tests/test_DetectorSensitivityArrays.cpp, tdms/tests/unit/array_tests/test_DispersiveMultiLayer.cpp, tdms/tests/unit/array_tests/test_FieldSample.cpp, tdms/tests/unit/array_tests/test_FrequencyVectors.cpp, tdms/tests/unit/array_tests/test_IncidentField.cpp, tdms/tests/unit/array_tests/test_Material.cpp, tdms/tests/unit/array_tests/test_Matrix.cpp, tdms/tests/unit/array_tests/test_Tensor3D.cpp, tdms/tests/unit/array_tests/test_Vector.cpp, tdms/tests/unit/array_tests/test_XYZTensor3D.cpp, tdms/tests/unit/array_tests/test_XYZVectors.cpp
Closes #165 | Hence also closes #136 |
- (~200 lines) Most important introduction (`AbstractArrayTest` class): [LINK](https://github.com/UCL/TDMS/blob/wgraham-array_test_class/tdms/tests/include/abstract_array_test_class.h)
- (~300 lines) A (very boring) long list of test class declarations: [LINK](https://github.com/UCL/TDMS/blob/wgraham-array_test_class/tdms/tests/include/array_test_class.h)
- Everything else is a refactor
---
Introduces the `AbstractArrayTest` class, using the template described [here](https://github.com/UCL/TDMS/pull/159#pullrequestreview-1178788597).
This class contains a number of virtual methods, which are designed to be overwritten by the subclasses that correspond to the individual arrays in `arrays.h`. Commonly executed tasks, like creation of MATLAB inputs, …
=> Test class for `array.h` classes

.github/workflows/doxygen-gh-pages.yml, README.md, doc/developers.md, tdms/CMakeLists.txt, tdms/cmake/targets.cmake, tdms/include/arrays.h, tdms/include/mesh_base.h, tdms/include/simulation_parameters.h, tdms/src/argument_parser.cpp, tdms/src/iterator.cpp, tdms/src/main.cpp, tdms/src/mesh_base.cpp, tdms/src/openandorder.cpp, tdms/src/simulation_parameters.cpp
There was a hanging documentation and a renaming task from our last meeting with Peter.
I also include a few minor sanity fixes: 
* I moved `main` into `main.cpp`.
* Fixed the broken `<details>` tags (or at least it's fixed with my local doxygen version).
* Updated the version of doxygen (I hope).
=> Rename phasorinc, add {C,D}Collection documentation, and `main()` → `main.cpp`

tdms/include/arrays.h, tdms/include/field.h, tdms/include/grid_labels.h, tdms/include/iterator.h, tdms/src/arrays.cpp, tdms/src/fields/base.cpp, tdms/src/fields/split.cpp, tdms/src/grid_labels.cpp, tdms/src/iterator.cpp, tdms/tests/include/array_test_class.h, tdms/tests/unit/array_tests/test_DispersiveMultiLayer.cpp, tdms/tests/unit/array_tests/test_XYZVectors.cpp
Attempting to do some small refactors to `iterator.cpp` that don't touch anything that will need to be touched by #70. Docstrings are added to all refactored functions, classes, etc.
Replaced with the `Field` class method `max_pointwise_difference_over_max_element`. The name of the old function is misleading, it is only computing an error metric and NOT checking convergence - this happens later in the `iterator.cpp` main loop.
Pulling this out into a class method to make things a bit cleaner. Also, both the inputs are `Field`s, and the function is asymmetric, so it makes sense to have this as a class method.
Changed to the `initialise_from` method of the `GridLabels` class.
Changed to `is_dispersive` method of `DispersiveMultilayer` class.
Superceeded by the `all_elements_less_than` …
=> Iterator refactor [3/N]

tdms/CMakeLists.txt
v1.10 → [v1.11](https://github.com/gabime/spdlog/releases/tag/v1.11.0)
=> Update spdlog version to v1.11.0.

.pre-commit-config.yaml
Clang-format during `pre-commit` now edits your files that it doesn't like with the correct code formatting, rather than just telling you what you're doing wrong.
=> Clang-format replaces in file

.github/workflows/doxygen-gh-pages.yml, README.md, doc/Doxyfile
This PR is the first part of #230. It makes three changes:
1. Adds README.md and CONTRIBUTING.md to the web pages (they appear in _that_ order in the ToC followed by the developer docs 👍). Screenshot below, and [live dev version over on my personal fork](https://scnlf.me/TDMS).
2. Uses MacOS/homebrew to install and run Doxygen 1.9.6 which is much cooler 😎 than the version we were previously using in ubuntu (1.9.2 👎 ). Amongst other improvements: the cool version correctly renders the `<details>` HTML tags.
3. Splits the Doxygen workflow into two steps: `doxygen` and `publish`. This has a couple of benefits...
* We can [run the first step (not the second)](https://github.com/samcunliffe/TDMS/actions/runs/4244369222) on all PRs and use it as an additional check that C++ code is documented. …
=> Add to Doxygen pages, and use doxygen as a CI check.

tdms/include/field.h, tdms/src/fields/td_field_exporter_2d.cpp, tdms/src/simulation_manager/objects_from_infile.cpp
3b0fcb3d6cbdf92425d46012bdfde3f6114d6dd7 fixes the problem with exporting the fields to a non-existent directory. And since I've got the context in my head, I replaced `char* folder_name` in the `TDFieldExporter2D` to an `std::string` and did some sanity refactoring in 9fbe3e70fd8c596c9584d7f0d4cc18d52f04567f.
Probably related to #211. Superficially fixes #255 (I retrospectively created a bug report) and fixes #129 (I forgot that we'd seen this before and it disappeared).
=> "Fix" M2 Mac `TDFieldExporter2D` problem.

.isort.cfg, pyproject.toml
`isort` uses a default linting style for long includes [that is incompatible with `black`s default](https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#isort). We have both in our pre-commit and do not resolve this conflict.
This PR adds a `pyproject.toml` to the repo to implement the recommended fix.
(This conflict has only just come to light because it only occurs when an `import` line is too long and needs to be wrapped. Working on #241 has bought this to light)
=> `isort` to make `black`-compatible changes

.github/workflows/ci.yml, .gitignore, README.md, doc/developers.md, tdms/CMakeLists.txt
Adds a coverage build to CMakeLists and additions to the GitHub action to upload it all to codecov.io.
* Fixes  #120 
* Adds a coverage build to CMakeLists. Currently, this is only for the `tdms_tests` executable. Could also add it to `tdms` itself if we wanted to check the system tests' coverage.
* In our CI GitHub action, I install `lcov` (for nice summaries of the coverage stats for humans, and for upload to [codecov.io](https://codecov.io/gh/UCL/TDMS)).
* Add a badge 🎉 (but we need to get a token before it will be meaningful).
Tested over on my fork.
* An example of the [build output](https://github.com/samcunliffe/TDMS/actions/runs/4796581423) (I temporarily disabled a whole bunch of irrelevant stuff in the build matrix).
* [What it looks like on …
=> Add coverage build and upload unit-test coverage to codecov.io

examples/arc_01/run_pstd_bscan.m
* Fixes #271 
Updates the additional path added to the `MATLABPATH` when running the example script, so that MATLAB can find the required files.
`examples/arc_01` can now be run using the instructions in the README.md and does not error.
=> Fix example script path

doc/developers.md, tdms/tests/system/data/input_generation/bscan/run_bscan.m, tdms/tests/system/data/input_generation/config_01.yaml, tdms/tests/system/data/input_generation/config_02.yaml, tdms/tests/system/data/input_generation/config_03.yaml, tdms/tests/system/data/input_generation/generate_test_input.py, tdms/tests/system/data/input_generation/input_file_02.m, tdms/tests/system/data/input_generation/input_file_03.m, tdms/tests/system/data/input_generation/matlab/scattering_matrix.m, tdms/tests/system/data/pyproject.toml, tdms/tests/system/test_regen.py
Continues #240 |
Adds `arc_02` and `arc_03` to the list of tests which are now covered by the input data regeneration scripts.
Modifications on top of #236:
- `run_bscan` now handles different spatial objects, obstacle radii, and when `illsetup` is required on top of the usual `filesetup`.
- `config_XX.yaml` and `input_file_XX.m` are added to the `data/input_generation` folder appropriately
- ~`generate_input_data.py` has been split into `bscan_arguments.py` and `generation_data.py` containing classes of the same name, to separate functionality.~
- ~Reduces the number of variables and input parameters that were stored more than once across the test classes~ (this is redundant because the classes now no longer exist in the base branch)
- `test_regen.py` will run tests in numerical order …
=> Track generation for `arc_02` and `arc_03`

tdms/tests/matlab/test_fdtdduration.m, tdms/tests/matlab/test_iteratefdtd_matrix.m, tdms/tests/system/data/input_generation/matlab/calc_field_tdfield.m, tdms/tests/system/data/input_generation/matlab/efield_gauss_base.m, tdms/tests/system/data/input_generation/matlab/efield_plane.m, tdms/tests/system/data/input_generation/matlab/fdtd_bounds.m, tdms/tests/system/data/input_generation/matlab/fdtdduration.m, tdms/tests/system/data/input_generation/matlab/fdtdts.m, tdms/tests/system/data/input_generation/matlab/file_parser/is_white_space.m, tdms/tests/system/data/input_generation/matlab/gauss_legendre.m, tdms/tests/system/data/input_generation/matlab/get_from_input_file.m, tdms/tests/system/data/input_generation/matlab/getsourcecoords.m, tdms/tests/system/data/input_generation/matlab/hfield_focused_equiv.m, tdms/tests/system/data/input_generation/matlab/import_constants.m, tdms/tests/system/data/input_generation/matlab/initialisesplitgrid.m, tdms/tests/system/data/input_generation/matlab/minsteps_fdtd.m, tdms/tests/system/data/input_generation/matlab/minsteps_pstd.m, tdms/tests/system/data/input_generation/matlab/multi_layer.m, tdms/tests/system/data/input_generation/matlab/yeeposition.m
Continues #236 | Related to #266 in that it adds a lot of docstrings and simplifies a lot of the codebase.
Now that the input data generation scripts are tracked by the repository, we can focus on tidying up the supporting `MATLAB` functions in the `matlab` folder to reduce code duplication, bloat, etc.
There are a _lot_ of docstring fixes, which the commit history logs pretty well. 
- `get_from_input_file` allows us to recycle the code chunk that appeared in almost all of the longer functions into one place. It also fetches the values in a safer manner than before (running `eval` over each line of a script sequentially), and it also means the linter doesn't complain when you open a file that has had a variable implicitly defined by an `eval` statement and not actually defined _properly_. …
=> General tidy up of `matlab` directory

tdms/include/arrays.h, tdms/include/utils.h, tdms/src/arrays.cpp, tdms/src/fields/td_field_exporter_2d.cpp, tdms/src/utils.cpp, tdms/tests/unit/test_utils.cpp
Doesn't hurt to test our utils but I'm mostly interested in the change in coverage for the utils.cpp file.
=> A kindof trivial test addition to help debug #279.

.github/workflows/ci.yml, .github/workflows/doxygen-gh-pages.yml, .github/workflows/matlab_tests.yml
Adding `merge_group:` to the CI checks we will want to build for a [merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue).
* First part of #287.
=> Add CI, MATLAB tests, and doxygen build to the `merge_group`.

tdms/cmake/targets.cmake, tdms/tests/include/unit_test_utils.h, tdms/tests/unit/array_tests/test_DTilde.cpp, tdms/tests/unit/hdf5_and_tdms_objects/test_hdf5_Cuboid.cpp, tdms/tests/unit/hdf5_and_tdms_objects/test_hdf5_DispersiveMultiLayer.cpp, tdms/tests/unit/hdf5_and_tdms_objects/test_hdf5_FrequencyVector.cpp, tdms/tests/unit/hdf5_and_tdms_objects/test_hdf5_InterfaceComponent.cpp, tdms/tests/unit/hdf5_io_tests/test_hdf5_dimension.cpp, tdms/tests/unit/hdf5_io_tests/test_hdf5_io.cpp, tdms/tests/unit/hdf5_io_tests/test_hdf5_reader.cpp, tdms/tests/unit/hdf5_io_tests/test_hdf5_writer.cpp
Possibly overkill but in the interest of small PRs (cough cough). Here is a tweak to your small data sample unit tests which skips them if the data not found. This is a PR against our draft branch from Friday (so you know what I'm proposing).
Still TODO: decide whether to provide instructions to generate them here in the logging. What do you think?
* Relates to #181 
* Targets #294
* Not `main`:
🐢
🐢
🐢
Checked locally with
```
➤ mv ../tdms/tests/unit/benchmark_scripts/unit_test_data ../tdms/tests/unit/benchmark_scripts/_unit_test_data
➤ ./tdms_tests
< ... blah blah ...>
===============================================================================
test cases:  51 |  43 passed | 8 skipped
assertions: 904 | 904 passed
➤ mv ../tdms/tests/unit/benchmark_scripts/_unit_test_data …
```
=> Minor tidy up, and skip the tests if no file is found.

README.md, tdms/include/interpolation_methods.h, tdms/tests/matlab/data/pstd_input_file_2D.m, tdms/tests/matlab/data/pstd_input_file_3D.m, tdms/tests/system/config_files/config_01.yaml, tdms/tests/system/data/input_generation/input_files/input_file_01.m, tdms/tests/system/data/input_generation/input_files/input_file_02.m, tdms/tests/system/data/input_generation/input_files/input_file_03.m, tdms/tests/system/data/input_generation/input_files/input_file_08.m, tdms/tests/system/data/input_generation/input_files/input_file_09.m, tdms/tests/system/data/input_generation/input_files/input_file_10.m, tdms/tests/system/data/input_generation/input_files/input_file_12.m, tdms/tests/system/data/input_generation/input_files/input_file_13.m, tdms/tests/system/data/input_generation/input_files/input_file_example_fdtd.m, tdms/tests/system/data/input_generation/matfile_option_edit.py, tdms/tests/system/data/input_generation/matlab/iteratefdtd_matrix.m, tdms/tests/system/read_config.py, tdms/tests/unit/matlab_benchmark_scripts/readme.md, tdms/tests/unit/test_BLi_vs_cubic_interpolation.cpp, tdms/tests/unit/test_interpolation_determination.cpp
=> Replace "band limited" with "bandlimited"

.github/workflows/ci.yml
Something is strange about the coverage reported by MacOS builds. Perhaps `llvm-cov`? Turning off whilst we investigate.
Relates to #279 and "solves" it by ignoring the problem.
Should improve the developers' quality of life. And will stop giving @codecovbot inconsistent reports.
=> Turn off coverage reporting in MacOS

.github/workflows/ci.yml, README.md, tdms/CMakeLists.txt, tdms/cmake/targets.cmake, tdms/include/hdf5_io.h, tdms/src/hdf5_io.cpp, tdms/tests/unit/test_hdf5_io.cpp
A cherry-pick of the first few commits of #250 for factorised review.
First part of (does not solve)
* #181 
Supercedes
* #193
*  #250
=> Add dependence on `libhdf5` and basic implementation class structure.

tdms/CMakeLists.txt
Our cmake instructions do not actually place our shared library into the correct install location, nor tell `tdms` where to find this library. This meant that `tdms` cannot find `libtdms_lib.so` at runtime unless `LD_LIBRARY_PATH` had been manually set.
This PR fixes that. Now if `tdms` is to be installed to `/foo/bar/bin`, `tdms_lib.so` will be placed in `/foo/bar/lib`. Additionally, the `rpath` of `tdms` has been set to include _both_ the MATLAB directory _and_ the library directory so users shouldn't need to do any manual pathing.
=> Install `libtdms_lib.so` correctly

README.md
Related to the discussion in
* #320 
I propose to add some "Troubleshooting" instructions to README.
Should the MATLAB file format v7.3 instructions also go _inside_ the troubleshooting `<details>` tags? I.e. Hidden by default.
Pros:
* Makes the README shorter and clearer(?)
* Shorter is gooder.
* Not everyone will want to save files in MATLAB.
* MATLAB file format issues are, strictly speaking, not our fault or our business.
Cons:
* The important help could get overlooked.
=> Add troubleshooting instructions to README.md

tdms/include/arrays.h, tdms/include/arrays/eh_vec.h, tdms/include/field.h, tdms/include/simulation_manager/simulation_manager.h, tdms/src/arrays.cpp, tdms/src/arrays/eh_vec.cpp, tdms/tests/include/array_test_class.h, tdms/tests/unit/array_tests/test_EHVec.cpp, tdms/tests/unit/array_tests/test_Matrix.cpp
The `EHVec` class is currently a public `Matrix<fftw_complex>`. It is desirable to convert `Matrix<>` to used strided vector storage and remove any MATLAB dependencies.
The former doesn't work for `EHVec` since the `fftw_complex` type is a double[2], which throws an error when used in templated `std::vector<T>` functions. Additionally, `EHVec` is used in such a way that `fftw` needs a continuous buffer to perform the forward/backward transform, which a strided vector does not guarantee.
As such, it is necessary to provide `EHVec` with it's own (MATLAB-free) class. This enables `Matrix` and its other derivatives to be freed of MATLAB influence.
* Concerns #285, resolves the `EHVec` task.
* Depends on #324, targets the expected state of `main`.
- Existing unit tests for `EHVec` continue to …
=> Detach the `EHVec` class from `Matrix`

tdms/include/hdf5_io/hdf5_base.h, tdms/include/hdf5_io/hdf5_reader.h, tdms/src/hdf5_io/hdf5_base.cpp, tdms/src/hdf5_io/hdf5_reader.cpp, tdms/src/simulation_manager/objects_from_infile.cpp, tdms/tests/unit/hdf5_and_tdms_objects/test_hdf5_Cuboid.cpp, tdms/tests/unit/hdf5_and_tdms_objects/test_hdf5_DispersiveMultiLayer.cpp, tdms/tests/unit/hdf5_and_tdms_objects/test_hdf5_FrequencyVector.cpp, tdms/tests/unit/hdf5_and_tdms_objects/test_hdf5_InterfaceComponent.cpp, tdms/tests/unit/hdf5_io_tests/test_hdf5_base.cpp, tdms/tests/unit/hdf5_io_tests/test_hdf5_dimension.cpp, tdms/tests/unit/hdf5_io_tests/test_hdf5_reader.cpp
Adds a `path_exists` function to the `HDF5Base` class, wrapping the `C++` API functions behind some nicer errors and cleaner functionality. This also superceeds that `exists` function that was written on the `181-pairdev-write-dataset-to-group` branch.
Also, it appears that most (read most, not all) of the HDF5 functions can handle paths from the file root, rather than needing to recursively open `Groups` and then `DataSets`. As a result, `read_dataset_from_group` is no longer needed as we can just overload `read()` to look directly at absolute paths.
- Tests added for `path_exists()` function.
- Existing tests for `read_dataset_in_group` have been set to use the new replacement method.
=> Clearer helper methods for `HDF5Base`

README.md
For some reason, the dynamic license badge always lags. Try a static one.
Minorest annoyingest of the PRs.
=> Static badge.

tdms/include/arrays.h, tdms/include/arrays/tdms_matrix.h, tdms/include/hdf5_io/hdf5_reader.h, tdms/include/hdf5_io/hdf5_writer.h, tdms/include/simulation_manager/objects_from_infile.h, tdms/include/simulation_manager/pstd_variables.h, tdms/include/vertex_phasors.h, tdms/src/arrays.cpp, tdms/src/arrays/tdms_matrix.cpp, tdms/src/hdf5_io/hdf5_writer.cpp, tdms/src/simulation_manager/execute_detector_subfunctions.cpp, tdms/src/simulation_manager/execute_simulation.cpp, tdms/src/simulation_manager/execute_update_Ex_split.cpp, tdms/src/simulation_manager/objects_from_infile.cpp, tdms/src/vertex_phasors.cpp, tdms/tests/include/array_test_class.h, tdms/tests/unit/array_tests/test_Matrix.cpp, tdms/tests/unit/hdf5_and_tdms_objects/test_hdf5_Matrix.cpp
Concerns #285:
- Completes the `Matrix` and `CCoefficientMatrix` tasks
- Moves towards the derived class objectives too.
- Also detaches `Pupil` from MATLAB
Converts the `Matrix` template class to a wrapper for strided vector storage.
Derived class behaviour changes:
- `CCoefficientMatrix` is now just a `typedef` for `Matrix<double>`.
- `Pupil` is a `struct` that inherits from `Matrix<double>`.
- `Vertices` & `GratingStructure` are `struct`s that inherit from `Matrix<int>`.
Although the only thing the derived "structs" now add is a unique way to read these classes via MATLAB. Once they have their `MATLAB` dependency removed, we can probably just typedef them all to `Matrix<double/int>`.
Tests are preserved for all existing classes.
=> Convert `Matrix` to a strided vector

tdms/cmake/version_from_git.cmake
The problem was that a detatched head has no `branchname`. But that is precisely what we're expecting if we 
```{sh}
git checkout v1.0.1
```
So we were entering the "branchname is not main" part of the if statement with an empty branchname.
Fixes 
* #325
Follows on from
* #203
=> No leading underscore in version.

tdms/src/argument_parser.cpp
As title. `tdms --version` is called in our CI so we should be able to get what [version of the OpenMP spec](https://github.com/Kitware/CMake/blob/master/Modules/FindOpenMP.cmake#L435). VisualStudio is obeying the Windows runners.
Up to you if we actually want to spit the OpenMP version spec out with `tdms --version`. I'd say it doesn't hurt.
=> Add the `_OPENMP` version (date of spec) to `tdms --version`

.github/workflows/ci.yml
Turns off `lcov` on the MacOS CI job. (It's failing due to some line number mismatch. Likely an upstream problem. And we definitely don't have the capacity to dive into this right now.
=> Don't run lcov on MacOS

.github/dependabot.yml
Update to [doxygen-awesome-css v2.3.4](https://github.com/jothepro/doxygen-awesome-css/releases/tag/v2.3.4).
This _should_ now only use a session cookie. And therefore _should_ fix
- #370
=> Update doxygen-awesome to v2.3.4
